name: Fetch Secrets & Perform an App Settings Variable Substitution
description: Fetch secrets from Azure KeyVault for an API/UI and update the App Settings with them

outputs:
  publish_profile:
    value: ${{ steps.fetch.outputs.publish_profile }}
    description: Publish profile to use for the deployment

inputs:
  keyvault_name:
    required: true
    type: string
    description: Key vault name without the prefix
  keyvault_prefix:
    required: true
    type: string
    description: The prefix of the KeyVault Key, e.g., IDAM-API-SECRET-NAME will have the prefix IDAM-API
  files:
    required: true
    description: Comma seperated list of files to update
    type: string
  configure:
    required: true
    type: choice
    options:
      - 'Applications'
      - 'Functions'
      - 'Tests'

runs:
  using: composite

  steps:
    - name: Fetch Secrets from Azure
      id: fetch
      shell: pwsh
      run: |-
        $names = az keyvault secret list --vault-name ${{ inputs.keyvault_name }} --query "[?starts_with(name, '${{ inputs.keyvault_prefix }}-')].name" --output json
        Write-Output "KeyVault Names = $names"
        $arr = $names | ConvertFrom-Json
        foreach ($item in $arr) {
          $key = $item -replace '${{ inputs.keyvault_prefix }}-',''
          $key = $key -replace '-','_'
          $value = az keyvault secret show --name $item --vault-name ${{ inputs.keyvault_name }} --query value --output tsv
          Write-Output "::add-mask::$value"
          if ($key -eq "AZURE_WEBAPP_PUBLISH_PROFILE")
          {
            Write-Output "publish_profile=$value" >> $env:GITHUB_OUTPUT
          }
          Write-Output "$key=$value" >> $env:GITHUB_OUTPUT
        }

      # Keys that aren't in an appsettings.json file and aren't in the fetch step's output are ignored ..
      # .. so each API / UI only populates what is relevant to it.
    - name: App Settings Variable Substitution
      if: inputs.configure == 'Applications'
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ inputs.files }}
      env:
        APPINSIGHTS_CONNECTION_STRING: ${{ steps.fetch.outputs.APPINSIGHTS_CONNECTION_STRING }}
        APPINSIGHTS_INSTRUMENTATIONKEY: ${{ steps.fetch.outputs.APPINSIGHTS_INSTRUMENTATIONKEY }}
        ConnectionStrings.IdamConnection: ${{ steps.fetch.outputs.CONNECTIONSTRINGS_IDAMCONNECTION }}
        Crypto.DbEncryptionIVKey: ${{ steps.fetch.outputs.CRYPTO_DBENCRYPTIONIVKEY }}
        Crypto.DbEncryptionKey: ${{ steps.fetch.outputs.CRYPTO_DBENCRYPTIONKEY }}
        GovUkOidcConfiguration.BearerTokenSigningKey: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_BEARERTOKENSIGNINGKEY }}
        ServiceDirectoryApiBaseUrl: ${{ steps.fetch.outputs.SERVICEDIRECTORYAPIBASEURL }}
        ConnectionStrings.ServiceDirectoryConnection: ${{ steps.fetch.outputs.CONNECTIONSTRINGS_SERVICEDIRECTORYCONNECTION }}
        GovNotifySetting.ManageAPIKey: ${{ steps.fetch.outputs.GOVNOTIFYSETTING_MANAGEAPIKEY }}
        GovNotifySetting.ConnectAPIKey: ${{ steps.fetch.outputs.GOVNOTIFYSETTING_CONNECTAPIKEY }}
        ConnectionStrings.NotificationConnection: ${{ steps.fetch.outputs.CONNECTIONSTRINGS_NOTIFICATIONCONNECTION }}
        ConnectionStrings.ReferralConnection: ${{ steps.fetch.outputs.CONNECTIONSTRINGS_REFERRALCONNECTION }}
        ConnectionStrings.ReportConnection: ${{ steps.fetch.outputs.CONNECTIONSTRINGS_REPORTCONNECTION }}
        FamilyHubsUi.Urls.ThisWeb: ${{ steps.fetch.outputs.FAMILYHUBSUI_URLS_THISWEB }}
        FamilyHubsUi.PathPrefix: ${{ steps.fetch.outputs.FAMILYHUBSUI_PATHPREFIX }}
        ServiceDirectoryUrl: ${{ steps.fetch.outputs.SERVICEDIRECTORYURL }}
        ReferralApiUrl: ${{ steps.fetch.outputs.REFERRALAPIURL }}
        Idams.Endpoint: ${{ steps.fetch.outputs.IDAMS_ENDPOINT }}
        FamilyHubsUi.Urls.GovUkLoginAccountPage: ${{ steps.fetch.outputs.FAMILYHUBSUI_URLS_GOVUKLOGINACCOUNTPAGE }}
        FamilyHubsUi.Urls.DashboardWeb: ${{ steps.fetch.outputs.FAMILYHUBSUI_URLS_DASHBOARDWEB }}
        DataProtection.KeyIdentifier: ${{ steps.fetch.outputs.DATAPROTECTION_KEYIDENTIFIER }}
        ConnectionStrings.SharedKernelConnection: ${{ steps.fetch.outputs.CONNECTIONSTRINGS_SHAREDKERNELCONNECTION }}
        ServiceDirectoryAPI.Endpoint: ${{ steps.fetch.outputs.SERVICEDIRECTORYAPI_ENDPOINT }}
        SqlServerCache.Connection: ${{ steps.fetch.outputs.SQLSERVERCACHE_CONNECTION }}
        CacheConnection: ${{ steps.fetch.outputs.CACHECONNECTION }}
        FamilyHubsUi.Urls.ConnectWeb: ${{ steps.fetch.outputs.FAMILYHUBSUI_URLS_CONNECTWEB }}
        FamilyHubsUi.Urls.FindWeb: ${{ steps.fetch.outputs.FAMILYHUBSUI_URLS_FINDWEB }}
        FamilyHubsUi.Urls.ManageWeb: ${{ steps.fetch.outputs.FAMILYHUBSUI_URLS_MANAGEWEB }}
        GovUkLoginAccountPage: ${{ steps.fetch.outputs.GOVUKLOGINACCOUNTPAGE }}
        GovUkOidcConfiguration.AppHost: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_APPHOST }}
        GovUkOidcConfiguration.IdamsApiBaseUrl: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_IDAMSAPIBASEURL }}
        GovUkOidcConfiguration.Oidc.BaseUrl: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_OIDC_BASEURL }}
        GovUkOidcConfiguration.Oidc.ClientId: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_OIDC_CLIENTID }}
        GovUkOidcConfiguration.Oidc.KeyVaultIdentifier: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_OIDC_KEYVAULTIDENTIFIER }}
        GovUkOidcConfiguration.Oidc.TwoFactorEnabled: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_OIDC_TWOFACTORENABLED }}
        GovUkOidcConfiguration.StubAuthentication.UseStubAuthentication: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_STUBAUTHENTICATION_USESTUBAUTHENTICATION }}
        GovUkOidcConfiguration.StubAuthentication.UseStubClaims: ${{ steps.fetch.outputs.GOVUKOIDCCONFIGURATION_STUBAUTHENTICATION_USESTUBCLAIMS }}
        IdamApi: ${{ steps.fetch.outputs.IDAMAPI }}
        Notification.Endpoint: ${{ steps.fetch.outputs.NOTIFICATION_ENDPOINT }}
        ReferralApiBaseUrl: ${{ steps.fetch.outputs.REFERRALAPIBASEURL }}
        ReportingApiBaseUrl: ${{ steps.fetch.outputs.REPORTINGAPIBASEURL }}
        FamilyHubsUi.Analytics.ContainerId: ${{ steps.fetch.outputs.FAMILYHUBSUI_ANALYTICS_CONTAINERID }}
        FamilyHubsUi.Analytics.MeasurementId: ${{ steps.fetch.outputs.FAMILYHUBSUI_ANALYTICS_MEASUREMENTID }}
        FamilyHubsUi.Analytics.ClarityId: ${{ steps.fetch.outputs.FAMILYHUBSUI_ANALYTICS_CLARITYID }}
        ConnectionStrings.HsdaMockResponsesConnection: ${{ steps.fetch.outputs.CONNECTIONSTRINGS_HSDAMOCKRESPONSESCONNECTION }}

    - name: Function Settings Variable Substitution
      if: inputs.configure == 'Functions'
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ inputs.files }}
      env:
        ApiConnection: ${{ steps.fetch.outputs.CONNECTIONAPI }}
        ServiceDirectoryConnection: ${{ steps.fetch.outputs.SERVICEDIRECTORYCONNECTION }}
        
    - name: Test Settings Variable Substitution
      if: inputs.configure == 'Tests'
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ inputs.files }}
      env:
        BaseUrl: ${{ steps.fetch.outputs.BASEURL }}
        BearerTokenSigningKey: ${{ steps.fetch.outputs.BEARERTOKENSIGNINGKEY }}   