name: Build & Test

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: ["main", "release-*", "test-linux-sd-tests"]
  pull_request:
    paths:
      - '.github/workflows/build-and-test.yml'
      - '.github/workflows/build-and-test-template.yml'
      - 'src/**'

jobs:
  build_and_test:
    name: ${{ matrix.job_name }}
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          [
            #service/notification-api,
            #service/idam-api,
            service/service-directory-api,
            #service/referral-api,
            #service/report-api,
            #ui/connect-dashboard-ui,
            #ui/connect-ui,
            #ui/find-ui,
            #ui/idam-maintenance-ui,
            #ui/manage-ui,
            #shared/referral-shared,
            #shared/service-directory-shared,
            #shared/shared-kernel,
            #shared/web-components
          ]
        include:
          #- working_directory: service/notification-api
          #  job_name: "Test - Notification API"
          #- working_directory: service/idam-api
          #  job_name: "Test - IDAM API"
          - working_directory: service/service-directory-api
            job_name: "Test - Service Directory API"
            #runs_on_windows: true
          #- working_directory: service/referral-api
          #  job_name: "Test - Referral API"
          #- working_directory: service/report-api
          #  job_name: "Test - Report API"
          #- working_directory: ui/connect-dashboard-ui
          #  job_name: "Test - Connect Dashboard UI"
          #- working_directory: ui/connect-ui
          #  job_name: "Test - Connect UI"
          #- working_directory: ui/find-ui
          #  job_name: "Test - Find UI"
          #- working_directory: ui/idam-maintenance-ui
          #  job_name: "Test - IDAM Maintenance UI"
          #- working_directory: ui/manage-ui
          #  job_name: "Test - Manage UI"
          #- working_directory: shared/referral-shared
          #  job_name: "Test - Referral Shared"
          #- working_directory: shared/service-directory-shared
          #  job_name: "Test - Service Directory Shared"
          #- working_directory: shared/shared-kernel
          #  job_name: "Test - Kernel Shared"
          #- working_directory: shared/web-components
          #  job_name: "Test - Web Components Shared"
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      working_directory: ${{ matrix.working_directory }}
      dotnet_version: ${{ vars.DOTNET_VERSION_V8 }}
      runs_on: ${{ matrix.runs_on_windows && 'windows-2022' || 'ubuntu-22.04' }}