name: Check Expiring App Certificates
#run-name: Deploy to ${{ inputs.environment }}

on:
  push:
    branches: ["feature/fhb-395-expiring-app-certs-action"]
  #schedule:
  #  - cron: '*/5 * * * *' # Every 5 mins
  
jobs:
  check-app-cert-expiry:
    name: Scheduled Check for App Expiring Certificates
    runs-on: 'ubuntu-22.04'
    environment: 'Development'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Check for App Expiring Certificates
        uses: ./.github/actions/expiring-app-certs