name: Check Expiring App Certificates
#run-name: Deploy to ${{ inputs.environment }}

on:
  push:
    branches: ["feature/fhb-395-expiring-app-certs-action"]
  #schedule:
  #  - cron: '*/5 * * * *' # Every 5 mins
  
jobs:
  check-app-cert-expiry:
    name: Scheduled Check for App Expiring Certificates
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Check for App Expiring Certificates
        uses: ./.github/actions/expiring-app-certs