name: Stryker

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: ["main", "release-*", "FHB-729"]
  pull_request:
    paths:
      - '.github/workflows/stryker.yml'
      - '.github/workflows/stryker-template.yml'
      - 'src/**'

jobs:
  stryker:
    name: ${{ matrix.job_name }}
    strategy:
      fail-fast: false
      matrix:
        project_directory:
          [
            src/FamilyHubs.ServiceDirectory.Api,
            src/FamilyHubs.ServiceDirectory.Core,
            src/FamilyHubs.Report.Api,
            src/FamilyHubs.Report.Core,
          ]
        include:
          - project_directory: src/FamilyHubs.ServiceDirectory.Api
            working_directory: service/service-directory-api
            job_name: "Stryker - Service Directory API - Api"
            runs_on_windows: true
          - project_directory: src/FamilyHubs.ServiceDirectory.Core
            working_directory: service/service-directory-api
            job_name: "Stryker - Service Directory API - Core"
            runs_on_windows: true
          - project_directory: src/FamilyHubs.Report.Api
            working_directory: service/report-api
            job_name: "Stryker - Report API - Api"
          - project_directory: src/FamilyHubs.Report.Core
            working_directory: service/report-api
            job_name: "Stryker - Report API - Core"
    uses: ./.github/workflows/stryker-template.yml
    with:
      working_directory: ${{ matrix.working_directory }}
      project_directory: ${{ matrix.project_directory }}
      runs_on: ${{ matrix.runs_on_windows && 'windows-2022' || 'ubuntu-22.04' }}
